HEX
FE000000 CONSTANT PERI_BASE
1	 CONSTANT OUTPUT

: GPIO_BASE PERI_BASE 200000 + ;
: GPSET0 GPIO_BASE 1C + ;
: GPCLR0 GPIO_BASE 28 + ;

: PIN ;
: ON/OFF-MASK 1 SWAP LSHIFT ;
: ON ON/OFF-MASK GPSET0 ! ;
: OFF ON/OFF-MASK GPCLR0 ! ;
: ENABLE-PINS 1224000 GPFSEL0 4 + ! ;


: ENABLE
	>R
	A /MOD
	SWAP >R
	4 * GPIO_BASE + DUP @
	R> 3 * DUP
	7 SWAP LSHIFT INVERT ROT AND
	R> rot LSHIFT OR
	SWAP ! ;


DECIMAL
