8 CONSTANT WORD_SIZE 

VARIABLE CURRENT_VALUE
VARIABLE LAST_VALUE
VARIABLE STATUS
VARIABLE OPERATION

: ADDITION ['] + ;
: SUBTRACTION ['] - ;
: MULTIPLICATION ['] * ;
: DIVISION ['] / ;

/ Bit twiddling 
: ?OVERFLOW [ 1 WORD_SIZE  1 - LSHIFT ] LITERAL > STATUS @ SWAP 
	IF 
		1 OR  
	ELSE
		[ 1 INVERT ] LITERAL AND
	THEN 
	STATUS ! ;
: ?NEGATIVE [ 1 31 LSHIFT ]  LITERAL AND 0 <> STATUS @ SWAP
	IF
		2 OR
	ELSE
		[ 2 INVERT ] LITERAL AND
	THEN
	STATUS ! ;

: TRUNCATE DUP ?OVERFLOW [ 1 WORD_SIZE LSHIFT ] LITERAL 1 - AND ;

: EXTEND_SIGN [ 1 WORD_SIZE 1 - LSHIFT ] LITERAL DUP ROT XOR SWAP - DUP ?NEGATIVE ;

: GET_RESULT ROT @ ROT @ ROT EXECUTE ;
: STORE_VALUE TRUNCATE EXTEND_SIGN CURRENT_VALUE ! ;


0 CURRENT_VALUE !
0 LAST_VALUE !
0 STATUS !
